### PR TITLE
Update Eclipse.download URLs

### LINKED ISSUE #42: Eclipse.package.recipe error packaging
The above mentioned recipe isn't working anymore as eclipse.org seems to have changed the URL scheme once more, please adjust accordingly. See below error message:

`The following recipes failed:
    Eclipse.pkg.recipe
        Error in com.github.sheagcraig.pkg.Eclipse: Processor: URLTextSearcher: Error: No match found on URL: https://eclipse.org/downloads/eclipse-packages/`

### PR DESCRIPTION
**Pull request by MichalMMac**
Fixes #42

### CODE REVIEW

**Comment by hfike** [comment]
I tested this change and it worked for the Eclipse IDE for Java Developers selection. After looking at your changes and the changes in the page, it might be better to remove some of the extra text that is being searched for on the page like this: https://github.com/autopkg/sheagcraig-recipes/pull/44

**Comment by MichalMMac** [comment]
Sure :-) More importantly we need to get @sheagcraig involved.

**Comment by sheagcraig** [comment]
Looks good to me gentlemen, but I'm not using this recipe currently.

BTW, the `\.` in the regexes is to match a literal period; otherwise `.` matches _anything_, which is not really the intended behavior I'm guessing. It's probably not an issue, but I feel like it's a good habit to match periods when you mean to match periods, so there aren't any surprises.

So @hfike and @MichalMMac can you give me some suggestions about which one of these PRs to merge?

**Comment by MichalMMac** [comment]
+1 for @hfike PR

**Comment by sheagcraig** [comment]
That works for me-thanks!

**Pull request closed without merging**
