### PR TITLE
Vivaldi new URL and Regex + Universal build

### PR DESCRIPTION
**Pull request by Bretterteig**
New base URL and Regex for download of universal build
Also: New signature

### CODE REVIEW

**Comment by adrienlabigne** [comment]
When this PR will be merged ?

**Comment by Bretterteig** [comment]
I fear the repo is currently inactive. Dont know if @sheagcraig is reviewing the PRs anytime soon

**Comment by macmule** [comment]
bump :)

`goes to bug Shea elsewhere`

**Comment by macmule** [comment]
Bump again :)

**Comment by homebysix** [comment]
Tested OK for me. I'll be merging this in, in support of https://github.com/autopkg/sheagcraig-recipes/issues/71.

Thank you!

```
% autopkg run -vv Vivaldi/Vivaldi.download.recipe 
Processing Vivaldi/Vivaldi.download.recipe...
WARNING: Vivaldi/Vivaldi.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'https:\\/\\/downloads\\.vivaldi\\.com\\/stable\\/Vivaldi[0-9\\.]+universal\\.dmg',
           'result_output_var_name': 'match',
           'url': 'https://vivaldi.com/download/'}}
URLTextSearcher: Found matching text (match): https://downloads.vivaldi.com/stable/Vivaldi.3.8.2259.40.universal.dmg
{'Output': {'match': 'https://downloads.vivaldi.com/stable/Vivaldi.3.8.2259.40.universal.dmg'}}
URLDownloader
{'Input': {'filename': 'Vivaldi.dmg',
           'url': 'https://downloads.vivaldi.com/stable/Vivaldi.3.8.2259.40.universal.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Wed, 05 May 2021 12:02:51 GMT
URLDownloader: Storing new ETag header: "6092896b-b4cf284"
URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.sheagcraig.download.Vivaldi/downloads/Vivaldi.dmg
{'Output': {'download_changed': True,
            'etag': '"6092896b-b4cf284"',
            'last_modified': 'Wed, 05 May 2021 12:02:51 GMT',
            'pathname': '~/Library/AutoPkg/Cache/com.github.sheagcraig.download.Vivaldi/downloads/Vivaldi.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '~/Library/AutoPkg/Cache/com.github.sheagcraig.download.Vivaldi/downloads/Vivaldi.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '~/Library/AutoPkg/Cache/com.github.sheagcraig.download.Vivaldi/downloads/Vivaldi.dmg/Vivaldi.app',
           'requirement': 'identifier "com.vivaldi.Vivaldi" and anchor apple '
                          'generic and certificate '
                          '1[field.1.2.840.113635.100.6.2.6] /* exists */ and '
                          'certificate leaf[field.1.2.840.113635.100.6.1.13] '
                          '/* exists */ and certificate leaf[subject.OU] = '
                          '"4XF3XNRN6Y"'}}
CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.sheagcraig.download.Vivaldi/downloads/Vivaldi.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.a6c9Ch/Vivaldi.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.a6c9Ch/Vivaldi.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.a6c9Ch/Vivaldi.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
Receipt written to ~/Library/AutoPkg/Cache/com.github.sheagcraig.download.Vivaldi/receipts/Vivaldi.download-receipt-20210508-125221.plist

The following new items were downloaded:
    Download Path                                                                                      
    -------------                                                                                      
    ~/Library/AutoPkg/Cache/com.github.sheagcraig.download.Vivaldi/downloads/Vivaldi.dmg
```

**Pull request merged**
